import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth, ClerkProvider, UserButton } from "@clerk/nextjs";
import { Sidebar } from "./_components/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Lock, Menu } from "lucide-react";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();
  console.log(userId);

  const valid = !userId || userId === "user_2ej7A9EyEVxrMOJxRT4cFsrwbcO";
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {valid ? (
            <div className="h-full">
              <Toaster />
              <div className="flex md:hidden h-10 p-3 bg-slate-500 items-center w-[100vw]">
                <Sheet>
                  <SheetTrigger>
                    <Menu className="text-gray-300" />
                  </SheetTrigger>
                  <SheetContent className="h-full w-80 p-0">
                    <Sidebar />
                  </SheetContent>
                </Sheet>
              </div>
              <div className="h-full flex flex-row">
                <div className="hidden md:flex h-full">
                  <Sidebar />
                </div>
                <main className="w-full">
                  {children}
                </main>
              </div>
            </div>
          ) : (
            <div className="h-full flex items-center justify-center">
              <div className="flex-col flex gap-y-2 text-center items-center justify-center">
                <Lock />
                <p className="text-sm text-center max-w-[480px]">
                  Ai! Uw account heeft geen rechten binnen deze applicatie. <br /><br />
                  Wij willen U laten herinneren dat als U deze applicatie wilt hacken,
                  heeft Republiek Hikeland, Politieke Partij Luchtballon, Ministerie
                  van ICT-technologieën van Hikeland, Parlement van Republiek Hikeland, Regering van Metropoolregio Groot-Miauwerheim <b><i>et cetera</i></b> volle recht om uw
                  IP-adres, persoonlijke informatie <b><i>et cetera</i></b> door te geven aan de
                  autoriteiten van Nederland, de EU, Zwitserland, Verenigde Staten <b><i>et cetera</i></b>. <br /><br />
                
                  Wij zien alle inlogpogingen van U of van een andere, samen met het desbetreffende IP-adres,
                  persoonlijke informatie, <b><i>et cetera</i></b>. <br />
                  <b>DIT IS GEEN BLUF!</b> <br /><br />
                  Heeft u op de verkeerde account ingelogd? <br />
                  U kunt via het gebruik van deze knop weer uitloggen:
                </p>
                <UserButton 
                  afterSignOutUrl="/"
                />
              </div>
            </div>
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}
